### ISSUE TITLE
 p2sh multisig verification test script 

### ISSUE THREAD

**Issue by zilveer** [Bit-Wasp/bitcoin-php#504] opened 2017-08-04 08:54 UTC
Hello,
lets say I generate a p2sh transaction and I would like to test its verification.
Is there any example out there showing how it is done?
I found a good python script for this [https://gist.github.com/badmofo/d45b847ab504f4aafa7d/](https://gist.github.com/badmofo/d45b847ab504f4aafa7d/)

Don't know if this is possible with BitWasp bitcoin library?

regards

**Comment by afk11** [comment] 2017-08-04 09:26
Yes you can already, it's in the example, but you should make double/triply sure you understand what script verification flags are before you use it.. You should set these: P2SH | DERSIG | CHECKLOCKTIMEVERIFY | CHECKSEQUENCEVERIFY | WITNESS

If setting these doesn't work on a valid tx, post back here right away ;)

https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/tx.spend.p2sh.p2wsh.php#L51

**Comment by zilveer** [comment] 2017-08-04 22:32
Hi,
Yes I do understand the script verification flags.

THE problem is that I am still pretty new to Bitwasp .
I am trying to help People when they post an issue so I can learn more.

But in this case I need your help I think.
Why is WITNESS needed ?

I am doing this for an Altcoin so I don't think WITNESS is needed here right?

If you can push me out the right direction I would appreciate it.

I have a signed raw tx hex code which I would like to validate but really don't know where to start.

All help is appreciated.

**Comment by afk11** [comment] 2017-08-05 09:13
Ah - for an altcoin without segwit, yea you don't need the flag. :) I'll write up a better example soon, but this should work once you have the details to fill in. Note that the txout is required, but since you're not using witness, the value is never checked (so can be left at zero)

The reason I am passing SignData in here (it _can_ be null for a fully signed tx, otherwise it's incomplete) is that the signer checks the txins redeemScript against that the one in SignData. Otherwise, the redeemScript in full isn't required, just the scriptPubKey. 

```
<?php

require __DIR__ . "/../vendor/autoload.php";

use BitWasp\Bitcoin\Script\Interpreter\InterpreterInterface as I;
use BitWasp\Bitcoin\Script\P2shScript;
use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Transaction\Factory\SignData;
use BitWasp\Bitcoin\Transaction\Factory\Signer;
use BitWasp\Bitcoin\Transaction\TransactionFactory;
use BitWasp\Bitcoin\Transaction\TransactionOutput;

$txHex = "01000000019421cafbbc70043c0d511c7edbca8dfb6b56610e0c2363144f3010d5157f19c200000000fc004730440220541172595b2d330fefffe6dae493ade63759a8d08f255324004de98be8fbe9eb0220175e9027e4020d36e8535a7a238777eea8bac8ff91cf131d13bf7b52b7b977c1014730440220541172595b2d330fefffe6dae493ade63759a8d08f255324004de98be8fbe9eb0220175e9027e4020d36e8535a7a238777eea8bac8ff91cf131d13bf7b52b7b977c1014c695221032d95156120a913f1e7f7274b632858395f933be1ca68e6ab08d4cc83448f493f21032d95156120a913f1e7f7274b632858395f933be1ca68e6ab08d4cc83448f493f21038d514c500e476f4b0e20f29ed19a697e4dc1c708ac798a6e2b81d902a1d4a8dc53aeffffffff01e0d5d505000000001976a9141627207f3d418fbe2734434d29692c3695cb79da88ac00000000";
$tx = TransactionFactory::fromHex($txHex);
$rs = new P2shScript(ScriptFactory::fromHex("5221032d95156120a913f1e7f7274b632858395f933be1ca68e6ab08d4cc83448f493f21032d95156120a913f1e7f7274b632858395f933be1ca68e6ab08d4cc83448f493f21038d514c500e476f4b0e20f29ed19a697e4dc1c708ac798a6e2b81d902a1d4a8dc53ae"));
$spk = $rs->getOutputScript();

$inputs = [
    [
        "sign" => (new SignData())->p2sh($rs),
        "txOut" => new TransactionOutput(0, $spk)
    ]
];

$flags = I::VERIFY_P2SH | I::VERIFY_DERSIG | I::VERIFY_CHECKLOCKTIMEVERIFY | I::VERIFY_CHECKSEQUENCEVERIFY;

$signer = new Signer($tx);
for ($i = 0, $n = count($inputs); $i < $n; $i++) {
    $input = $signer->input($i, $inputs[$i]["txOut"], $inputs[$i]["sign"]);
    if (!$input->verify($flags)) {
        throw new \RuntimeException("Invalid input $i");
    }
}

```

**Comment by afk11** [comment] 2017-08-05 09:15
Btw, for this stuff, I would really suggest you install this.. https://github.com/Bit-Wasp/bitcoinconsensus-php/tree/2.0.0 Basically, you can compile PHP bindings to the bitcoinconsensus.h library exposed by Bitcoin Core, so you don't have to trust the libraries re-implemented version.

**Comment by zilveer** [comment] 2017-08-05 22:00
@afk11 thank you for the example and the explanations.

may I ask why the redeemScript is needed?
`$rs = new P2shScript(ScriptFactory::fromHex("5221032d95156120a913f1e7f7274b632858395f933be1ca68e6ab08d4cc83448f493f21032d95156120a913f1e7f7274b632858395f933be1ca68e6ab08d4cc83448f493f21038d514c500e476f4b0e20f29ed19a697e4dc1c708ac798a6e2b81d902a1d4a8dc53ae"));`

Isn't only the TX hex needed to make the verification?

I presume that the TX hex is the generated multisig transaction TX hex, and that the redeemScript belongs to the multisig address correct?

**Comment by zilveer** [comment] 2017-08-05 22:21
@afk11 
I tested this and changed the txHex and rs for an altcoin (Blackcoin). I created a transaction and used the multisigs redeemScript but I get an error:

```
$txHex = "01000000653f8659014fe8571d87c5a931097c5f97819812b48f5380c49684b970722e33bf779837b001000000475221037d72903d0a671b9494d84ab2ca556d8cb4b49fd357652c3825f16170eb4d1dd82103f46a3f7b501870a525e08e69defabefc8320a29bcd6939b2c31103eed38e1b9552aeffffffff01e0d14d000000000017a91448fac3694683c2cd42663fe9c0f0504907a0d6598700000000";
$rs = new P2shScript(ScriptFactory::fromHex("5221037d72903d0a671b9494d84ab2ca556d8cb4b49fd357652c3825f16170eb4d1dd82103f46a3f7b501870a525e08e69defabefc8320a29bcd6939b2c31103eed38e1b9552ae"));

$tx = TransactionFactory::fromHex($txHex);

```

The error message I get is:
```
Fatal error: Uncaught exception 'BitWasp\Buffertools\Exceptions\ParserOutOfRange' with message 'Insufficient data remaining for VarString' in 
bitwasp/vendor/bitwasp/buffertools/src/Buffertools/Types/VarString.php:53 Stack trace: #0 
```

What is the issue here?

**Comment by afk11** [comment] 2017-08-06 09:16
@zilveer you need the scriptPubKey, which is reproduced by it's redeemScript. Since I already had an example that spits out redeemScripts and signed transactions, it was easiest to take the RS and use it. (a signed transaction already has it's redeemScript included, so only spk is needed).

Regarding the tx and rsHex for Blackcoin:

Hmm, bitcoind can't seem to parse that either. It looks like it's supposed to have 0x65 inputs though which seems wrong. (aside: I should really improve those error messages) Can you find a document describing Blackcoins p2p wire format? Maybe just compare that with https://en.bitcoin.it/wiki/Protocol_documentation#tx. You're going to run into trouble if they're different.

Also, it looks like that input is missing signatures - it only has the redeemScript.

**Comment by zilveer** [comment] 2017-08-06 15:52
Hi,
thanks for your reply.

You are correct, I missed to signed the TX hex.

The signed TX hex is
```
01000000653f8659014fe8571d87c5a931097c5f97819812b48f5380c49684b970722e33bf779837b0010000009200483045022100c3e24f2c4ad25b220d70bdfafe5ec618a5ed72cb09830359e2797ab337c9f74502200ec068bc9bf2d4530578e16fc2bdbf1f001d775cec0a421589b1fdc66f28c4a901475221037d72903d0a671b9494d84ab2ca556d8cb4b49fd357652c3825f16170eb4d1dd82103f46a3f7b501870a525e08e69defabefc8320a29bcd6939b2c31103eed38e1b9552aeffffffff01e0d14d000000000017a91448fac3694683c2cd42663fe9c0f0504907a0d6598700000000
```

The decoderawtransaction looks like this on the daemon:
```
{
    "txid" : "97be9949faf548016b2beb0dae2444d011f62a3cb400e5acb4a2cdf7d35bf693",
    "version" : 1,
    "time" : 1501970277,
    "locktime" : 0,
    "vin" : [
        {
            "txid" : "b0379877bf332e7270b98496c480538fb4129881975f7c0931a9c5871d57e84f",
            "vout" : 1,
            "scriptSig" : {
                "asm" : "0 3045022100c3e24f2c4ad25b220d70bdfafe5ec618a5ed72cb09830359e2797ab337c9f74502200ec068bc9bf2d4530578e16fc2bdbf1f001d775cec0a421589b1fdc66f28c4a901 5221037d72903d0a671b9494d84ab2ca556d8cb4b49fd357652c3825f16170eb4d1dd82103f46a3f7b501870a525e08e69defabefc8320a29bcd6939b2c31103eed38e1b9552ae",
                "hex" : "00483045022100c3e24f2c4ad25b220d70bdfafe5ec618a5ed72cb09830359e2797ab337c9f74502200ec068bc9bf2d4530578e16fc2bdbf1f001d775cec0a421589b1fdc66f28c4a901475221037d72903d0a671b9494d84ab2ca556d8cb4b49fd357652c3825f16170eb4d1dd82103f46a3f7b501870a525e08e69defabefc8320a29bcd6939b2c31103eed38e1b9552ae"
            },
            "sequence" : 4294967295
        }
    ],
    "vout" : [
        {
            "value" : 0.05100000,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "OP_HASH160 48fac3694683c2cd42663fe9c0f0504907a0d659 OP_EQUAL",
                "hex" : "a91448fac3694683c2cd42663fe9c0f0504907a0d65987",
                "reqSigs" : 1,
                "type" : "scripthash",
                "addresses" : [
                    "bKP9kPDRU3KSiRCLXnMHNFLjoeYHEcPRYh"
                ]
            }
        }
    ]
}
```

As you can see, the only difference on the protocol is the extra "time" field. Will I still have the issue to get the validation of the TX hex with Bitwasp? Perhaps, it is possible to add the time field as an option? It should be set to UTC time.

I have added the following to the NetworkFactory.php file:
```
	public static function blackcoin()
    {
        $network = self::create('19', '55', '99')
            ->setHDPubByte('02cfbf60')
            ->setHDPrivByte('02cfbede')
            ->setNetMagicBytes('70352205');
        return $network;
    }
```

Your help is really appreciated!
Regards

**Comment by zilveer** [comment] 2017-08-10 22:20
Any ideas on how to Solve this ?

**Comment by afk11** [comment] 2017-08-11 08:55
Is time supposed to be serialized into the transaction or is that just what the RPC is giving you? Bitcoin transactions aren't timestamped except for being added to blocks. It could just be in the RPC output?

**Comment by zilveer** [comment] 2017-08-11 21:13
Thanks for the long waited reply :)

No it should be serialized, upon decoderawtransaction it will be shown the timestamp in UTC.

I really would like to get in touch with you privately.
Can you email me ?
My email is zilveer@gmail.com

**Comment by zilveer** [comment] 2017-08-12 12:26
Any ideas on how to serialize it in the RAW TX?
There is a need to deserialize it as well later on.

Thanks for your reply.

**Comment by afk11** [comment] 2017-08-16 12:32
I think you'll need to write a new TransactionSerializer class, and a custom Transaction class (extending the normal one) that exposes the time. You can then override your Transaction::getBuffer method to use new serializer capable of read/writing the timestamp.

**Comment by zilveer** [comment] 2017-08-22 20:39
Thx for replting.i will see what I can do if I am capable of doing it

**Comment by afk11** [comment] 2017-09-16 22:05
Going to close this, it's a bit off topic for here, but if you've found the serialization for transaction time and are stuck with the types or anything, just let me know

**Closed by afk11** 2017-09-16 22:05 UTC
