### ISSUE TITLE
How to generate valid derived public addressed (on test network)

### ISSUE THREAD

**Issue by lezhnev74** [Bit-Wasp/bitcoin-php#566] opened 2017-11-24 11:19 UTC
Hi, I am practicing generating multiple derived addresses from single master public address.

This code gives me an address:
```php
$master_pub = "tpubD9EDMRKYRLyZNCZxvJDS6tueAkDVjdajrVZGv7rmPoaNZZEUGX5HJvDnBKi5EVG7ivx9tAcbjjEhEHwdkox3pP5iKQZ9FVFHHZoimQ5HwVh";

$key = HierarchicalKeyFactory::fromExtended($master_pub, NetworkFactory::bitcoinTestnet());

echo $key->derivePath("0/0")->getPublicKey()->getAddress()->getAddress();
// addr: 1DtkafCbLYJ2VJJZF4ws5uhnUyMUBitXTj
```

But it fails validation on testnet blockchain explorer: 
https://www.blocktrail.com/tBTC/address/1DtkafCbLYJ2VJJZF4ws5uhnUyMUBitXTj

Why is that, what am I doing wrong?

**Comment by afk11** [comment] 2017-11-24 15:35
Hmm, addresses don't have a definite size when encoded, it's possible there's a sanity check failing on blocktrail since bitcoind says it's valid too.

**Comment by afk11** [comment] 2017-12-07 20:47
Hey, wait a second, you were putting that address onto testnet! I don't know how that escaped me. Of course it's invalid.

**Comment by afk11** [comment] 2017-12-07 20:48
@lezhnev74 Hey, I see what the problem is now, you're querying testnet! That's why it's invalid, that's a mainnet address :)

**Comment by lezhnev74** [comment] 2017-12-08 05:26
@afk11 thanks for detailed examples! I will try them and will get back to this thread.

**Comment by afk11** [comment] 2017-12-08 11:37
No worries at all! Would happily accept suggestions on make it a bit safer to use also. I don't want people to feel forced into setting the network globally to avoid these cases. 

Might write something that would cause `Bitcoin::getNetwork()` to throw a DefaultsDisabledException if the default is ever relied upon so there's a way to guarantee run-time safety (even if you were consciously making an effort to pass the network everywhere, all it takes is forgetting in one place to cause application errors or having funds sent to the wrong network)

**Comment by lezhnev74** [comment] 2018-01-29 20:36
Hi, @afk11, sorry for long response! I continued testing the lib, but it seems API has been changed.
The code samples no more work, particularly the code:
```php
\BitWasp\Bitcoin\Bitcoin::setNetwork(NetworkFactory::bitcoin());
$key = HierarchicalKeyFactory::fromExtended($master_pub);
echo $key->derivePath("0/0")->getPublicKey()->getAddress()->getAddress();
```

Gives:
```
PHP Fatal error:  Uncaught Error: Call to undefined method BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey::getAddress() in /Users/dmitriylezhnev/Code/tests/bitcoin-php/fp.php:13
Stack trace:
#0 {main}
  thrown in /Users/dmitriylezhnev/Code/tests/bitcoin-php/fp.php on line 13

Fatal error: Uncaught Error: Call to undefined method BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey::getAddress() in /Users/dmitriylezhnev/Code/tests/bitcoin-php/fp.php:13
Stack trace:
#0 {main}
  thrown in /Users/dmitriylezhnev/Code/tests/bitcoin-php/fp.php on line 13
```

What I am trying to achieve is generate a bunch of derived addresses from given master pub address.

I would appreciate your advice how it is best done here.
Thank you for help!

**Comment by afk11** [comment] 2018-01-30 23:32
Replacing the last line with this should do it: 

```php
$publicKey = $key->derivePath("0/0")->getPublicKey();
$address = new PayToPubKeyHashAddress($publicKey->getPubKeyHash());
echo $address->getAddress() . PHP_EOL;
```

**Comment by afk11** [comment] 2018-03-18 19:11
Closing, query resolved.

**Closed by afk11** 2018-03-18 19:11 UTC
Labels: documentation, question
